// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace graduationProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250203023217_Newonecreate")]
    partial class Newonecreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DietPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DietPlans");
                });

            modelBuilder.Entity("Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("DietaryRestrictions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FitnessLevel")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Goal")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("MedicalConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreferredDiet")
                        .HasColumnType("int");

                    b.Property<int>("WeeklyWorkoutDays")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<string>("WorkoutDuration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("graduationProject.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("graduationProject.Models.GeneratedDietPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MealPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GeneratedDietPlans");
                });

            modelBuilder.Entity("graduationProject.Models.GeneratedWorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GeneratedWorkoutPlans");
                });

            modelBuilder.Entity("graduationProject.Models.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ARM"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chest"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ABS"
                        },
                        new
                        {
                            Id = 4,
                            Name = "LEG"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Back & Shoulder"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Stretches"
                        });
                });

            modelBuilder.Entity("graduationProject.Models.NutritionalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NutritionalInfos");
                });

            modelBuilder.Entity("graduationProject.Models.StructuredDietPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StructuredDietPlans");
                });

            modelBuilder.Entity("graduationProject.Models.StructuredWorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StructuredWorkoutPlans");
                });

            modelBuilder.Entity("graduationProject.Models.nExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("nExercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "https://img.youtube.com/vi/3DH2fwV5u1k/maxresdefault.jpg",
                            MuscleGroupId = 1,
                            Name = "Overhead Extension",
                            Sets = "3*12",
                            VideoUrl = "https://www.youtube.com/embed/3DH2fwV5u1k"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "https://img.youtube.com/vi/SNFj4cBJ6ds/maxresdefault.jpg",
                            MuscleGroupId = 1,
                            Name = "Dumbbell Press",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/SNFj4cBJ6ds"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "https://img.youtube.com/vi/tPAkjMLWvCY/maxresdefault.jpg",
                            MuscleGroupId = 1,
                            Name = "Tricep Dips",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/tPAkjMLWvCY"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "https://img.youtube.com/vi/sz_BVxduUWE/maxresdefault.jpg",
                            MuscleGroupId = 1,
                            Name = "Dumbbell Pullover",
                            Sets = "3*12",
                            VideoUrl = "https://www.youtube.com/embed/sz_BVxduUWE"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "https://img.youtube.com/vi/dsRNsZHuUkw/maxresdefault.jpg",
                            MuscleGroupId = 1,
                            Name = "Concentration Curl",
                            Sets = "3*12",
                            VideoUrl = "https://www.youtube.com/embed/dsRNsZHuUkw"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "https://img.youtube.com/vi/BneGVmsYBTY/maxresdefault.jpg",
                            MuscleGroupId = 1,
                            Name = "Cable Reverse",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/BneGVmsYBTY"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "https://img.youtube.com/vi/KVT2n9CpqRU/maxresdefault.jpg",
                            MuscleGroupId = 2,
                            Name = "Cable Crossovers",
                            Sets = "3*12",
                            VideoUrl = "https://www.youtube.com/embed/KVT2n9CpqRU"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "https://img.youtube.com/vi/W1qukYP2FLA/maxresdefault.jpg",
                            MuscleGroupId = 2,
                            Name = "Chest Press",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/W1qukYP2FLA"
                        },
                        new
                        {
                            Id = 9,
                            Icon = "https://img.youtube.com/vi/WU_AUjGaHnM/maxresdefault.jpg",
                            MuscleGroupId = 2,
                            Name = "Dumbbell Chest",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/WU_AUjGaHnM"
                        },
                        new
                        {
                            Id = 10,
                            Icon = "https://img.youtube.com/vi/OAps0BeSd7Y/maxresdefault.jpg",
                            MuscleGroupId = 2,
                            Name = "Dumbbell Fly",
                            Sets = "3*12",
                            VideoUrl = "https://www.youtube.com/embed/OAps0BeSd7Y"
                        },
                        new
                        {
                            Id = 11,
                            Icon = "https://img.youtube.com/vi/mATfjUjXr60/maxresdefault.jpg",
                            MuscleGroupId = 2,
                            Name = "Band Bench Press",
                            Sets = "3*12",
                            VideoUrl = "https://www.youtube.com/embed/mATfjUjXr60"
                        },
                        new
                        {
                            Id = 12,
                            Icon = "https://img.youtube.com/vi/WfFWsolPlP8/maxresdefault.jpg",
                            MuscleGroupId = 3,
                            Name = "Weighted Crunch",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/WfFWsolPlP8"
                        },
                        new
                        {
                            Id = 13,
                            Icon = "https://img.youtube.com/vi/cK2VIjqK4PY/maxresdefault.jpg",
                            MuscleGroupId = 3,
                            Name = "Rotating Stomach",
                            Sets = "3*12",
                            VideoUrl = "https://www.youtube.com/embed/cK2VIjqK4PY?si=-JIDMS5GRjBU_2PI"
                        },
                        new
                        {
                            Id = 14,
                            Icon = "https://img.youtube.com/vi/iZOAVk8qjjU/maxresdefault.jpg",
                            MuscleGroupId = 3,
                            Name = "Cable Crunch",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/iZOAVk8qjjU"
                        },
                        new
                        {
                            Id = 15,
                            Icon = "https://img.youtube.com/vi/jZYon72vEtU/maxresdefault.jpg",
                            MuscleGroupId = 3,
                            Name = "Leg Reverse Crunch",
                            Sets = "3*12",
                            VideoUrl = "https://www.youtube.com/embed/jZYon72vEtU"
                        },
                        new
                        {
                            Id = 16,
                            Icon = "https://img.youtube.com/vi/-uQO2gG8sjk/maxresdefault.jpg",
                            MuscleGroupId = 3,
                            Name = " Seated Crunch",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/-uQO2gG8sjk"
                        },
                        new
                        {
                            Id = 17,
                            Icon = "https://img.youtube.com/vi/1SaYpphpQ5w/maxresdefault.jpg",
                            MuscleGroupId = 4,
                            Name = "Leg Curl",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/1SaYpphpQ5w"
                        },
                        new
                        {
                            Id = 18,
                            Icon = "https://img.youtube.com/vi/weVucBtUl7I/maxresdefault.jpg",
                            MuscleGroupId = 4,
                            Name = "Low Bar Squat",
                            Sets = "3*12",
                            VideoUrl = "https://www.youtube.com/embed/weVucBtUl7I"
                        },
                        new
                        {
                            Id = 19,
                            Icon = "https://img.youtube.com/vi/aL3VFTD_4ew/maxresdefault.jpg",
                            MuscleGroupId = 4,
                            Name = "Smith Deadlift",
                            Sets = "3*12",
                            VideoUrl = "https://www.youtube.com/embed/aL3VFTD_4ew"
                        },
                        new
                        {
                            Id = 20,
                            Icon = "https://img.youtube.com/vi/myNurJqfgDc/maxresdefault.jpg",
                            MuscleGroupId = 4,
                            Name = "Leg Press",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/myNurJqfgDc"
                        },
                        new
                        {
                            Id = 21,
                            Icon = "https://img.youtube.com/vi/qvCOYW80akQ/maxresdefault.jpg",
                            MuscleGroupId = 4,
                            Name = "Standing Calf Raises",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/qvCOYW80akQ"
                        },
                        new
                        {
                            Id = 22,
                            Icon = "https://img.youtube.com/vi/33sUKgU3yjI/maxresdefault.jpg",
                            MuscleGroupId = 4,
                            Name = "Hip Abduction",
                            Sets = "3*12",
                            VideoUrl = "https://www.youtube.com/embed/33sUKgU3yjI"
                        },
                        new
                        {
                            Id = 23,
                            Icon = "https://img.youtube.com/vi/hghkuX7ejVo/maxresdefault.jpg",
                            MuscleGroupId = 4,
                            Name = "Hip Thrusts",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/hghkuX7ejVo"
                        },
                        new
                        {
                            Id = 24,
                            Icon = "https://img.youtube.com/vi/2Zbv0h5OA3I/maxresdefault.jpg",
                            MuscleGroupId = 4,
                            Name = "Barbell Lunge",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/2Zbv0h5OA3I"
                        },
                        new
                        {
                            Id = 25,
                            Icon = "https://img.youtube.com/vi/EQZvNNjCCPM/maxresdefault.jpg",
                            MuscleGroupId = 5,
                            Name = "Cable Elevated Row",
                            Sets = "3*12",
                            VideoUrl = "https://www.youtube.com/embed/EQZvNNjCCPM"
                        },
                        new
                        {
                            Id = 26,
                            Icon = "https://img.youtube.com/vi/T-wcu8iRSW4/maxresdefault.jpg",
                            MuscleGroupId = 5,
                            Name = "Cable Arm Pulldown",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/T-wcu8iRSW4"
                        },
                        new
                        {
                            Id = 27,
                            Icon = "https://img.youtube.com/vi/XsN8glqhebU/maxresdefault.jpg",
                            MuscleGroupId = 5,
                            Name = "Reverse Fly",
                            Sets = "3*12",
                            VideoUrl = "https://www.youtube.com/embed/XsN8glqhebU"
                        },
                        new
                        {
                            Id = 28,
                            Icon = "https://img.youtube.com/vi/LGjNc2nKYsk/maxresdefault.jpg",
                            MuscleGroupId = 5,
                            Name = "Lying T Bar Back",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/LGjNc2nKYsk"
                        },
                        new
                        {
                            Id = 29,
                            Icon = "https://img.youtube.com/vi/imkOFyqxNUc/maxresdefault.jpg",
                            MuscleGroupId = 5,
                            Name = "Cable Pulldown",
                            Sets = "3*12",
                            VideoUrl = "https://www.youtube.com/embed/imkOFyqxNUc"
                        },
                        new
                        {
                            Id = 30,
                            Icon = "https://img.youtube.com/vi/anxZfYAXmsY/maxresdefault.jpg",
                            MuscleGroupId = 5,
                            Name = "Dumbbell Press",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/anxZfYAXmsY"
                        },
                        new
                        {
                            Id = 31,
                            Icon = "https://img.youtube.com/vi/U79gWoPFNMU/maxresdefault.jpg",
                            MuscleGroupId = 5,
                            Name = "Cuban Press",
                            Sets = "3*12",
                            VideoUrl = "https://www.youtube.com/embed/U79gWoPFNMU"
                        },
                        new
                        {
                            Id = 32,
                            Icon = "https://img.youtube.com/vi/BEazZDwwns0/maxresdefault.jpg",
                            MuscleGroupId = 5,
                            Name = "Raise Plate",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/BEazZDwwns0"
                        },
                        new
                        {
                            Id = 33,
                            Icon = "https://img.youtube.com/vi/YkvgWqV9SuU/maxresdefault.jpg",
                            MuscleGroupId = 6,
                            Name = "Lying Cross Over",
                            Sets = "3*12",
                            VideoUrl = "https://www.youtube.com/embed/YkvgWqV9SuU"
                        },
                        new
                        {
                            Id = 34,
                            Icon = "https://img.youtube.com/vi/UzLl2wWApDM/maxresdefault.jpg",
                            MuscleGroupId = 6,
                            Name = "Crouching Heel Stretch",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/UzLl2wWApDM"
                        },
                        new
                        {
                            Id = 35,
                            Icon = "https://img.youtube.com/vi/1qVP0Sz-jhE/maxresdefault.jpg",
                            MuscleGroupId = 6,
                            Name = "Kneeling Toe Up Stretch",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/1qVP0Sz-jhE"
                        },
                        new
                        {
                            Id = 36,
                            Icon = "https://img.youtube.com/vi/sJ7FLxLCqe8/maxresdefault.jpg",
                            MuscleGroupId = 6,
                            Name = "Single Lean Back Stretch",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/sJ7FLxLCqe8"
                        },
                        new
                        {
                            Id = 37,
                            Icon = "https://img.youtube.com/vi/W-4JfmbiEl8/maxresdefault.jpg",
                            MuscleGroupId = 6,
                            Name = "Back Pec Stretch",
                            Sets = "3*10",
                            VideoUrl = "https://www.youtube.com/embed/W-4JfmbiEl8"
                        });
                });

            modelBuilder.Entity("Exercise", b =>
                {
                    b.HasOne("WorkoutPlan", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutPlanId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("graduationProject.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("graduationProject.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("graduationProject.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("graduationProject.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("graduationProject.Models.GeneratedDietPlan", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("graduationProject.Models.GeneratedWorkoutPlan", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("graduationProject.Models.StructuredDietPlan", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("StructuredDietPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("graduationProject.Models.StructuredWorkoutPlan", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("StructuredWorkoutPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("graduationProject.Models.nExercise", b =>
                {
                    b.HasOne("graduationProject.Models.MuscleGroup", "MuscleGroup")
                        .WithMany("nExercises")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("StructuredDietPlans");

                    b.Navigation("StructuredWorkoutPlans");
                });

            modelBuilder.Entity("WorkoutPlan", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("graduationProject.Models.MuscleGroup", b =>
                {
                    b.Navigation("nExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
